create table conf_session (
    id        bigint generated by default as identity primary key,
    title     varchar(200) not null,
    speaker   varchar(120) not null,
    room      varchar(60),
    starts_at timestamp    not null
);

create table feedback (
    id             bigint generated by default as identity primary key,
    session_id     bigint       not null references conf_session (id),
    attendee_email varchar(200) not null,
    rating         integer      not null,
    comments       varchar(500),
    submitted_at   timestamp    not null
);

create index idx_feedback_session on feedback (session_id);
